Remove maps from data preperation and from dashboard.
covid-19-impact-lab/utilities pull request #18
Opened 2021-04-20 08:42 UTC by baharcos

2021-05-10 16:42 UTC, roecla commented on utilities/dashboard/components/intro_page/create_data.py
> +        res["bottom_title"] = "Arbeitskräfteangebot"
```suggestion
        res["bottom_title"] = "Arbeitsangebot"
```

2021-05-10 17:32 UTC, roecla requested changes
- There are no more references to maps in the code but in the docs there still are. It would be great if you could search the repository for `maps` and update all references (e.g. the how to add a component guide). Otherwise, this might be confusing in the future. 
- `utilities/dashboard/components/univariate_distributions/metadata/.DS_Store` should not be part of the repository
- When running the dashboard in German I still get English texts. The outcome and split by variables are also not translated.

2021-05-10 17:32 UTC, roecla commented on utilities/dashboard/components/univariate_distributions/create_data.py
> +    ] = "How Does the CoVid-19 Pandemic Affect Different Groups?"
This should be different depending on the chosen language. In case of German it should read "Wie sind unterschiedliche Gruppen von der Corona Pandemie betroffen?"

2021-05-10 17:32 UTC, roecla commented on utilities/dashboard/app/main.py
>              "Arbeitskräfteangebot",
"Arbeitsangebot" and you must Remove the "Karten" (= maps) part from the tab_names. We only have three tabs now.

2021-05-10 17:34 UTC, roecla commented on utilities/dashboard/app/main.py
>              "Arbeitskräfteangebot",
And some German signs are not rendered correctly. E.g. in the group differences tab on the default values "Für" is not rendered correctly.

2021-05-13 19:55 UTC, baharcos commented on utilities/dashboard/components/univariate_distributions/create_data.py
> +    ] = "How Does the CoVid-19 Pandemic Affect Different Groups?"
All should be fixed now.

2021-05-13 23:56 UTC, baharcos commented on utilities/dashboard/app/main.py
>              "Arbeitskräfteangebot",
The charecters were missing also in .csv file on my mashine. I fixed it and changed the encoding from latin3 to utf8.

2021-05-18 06:59 UTC, roecla requested changes
The work supply is still not completely translated:

![image](https://user-images.githubusercontent.com/9567321/118606105-4e91ac80-b7b7-11eb-85b0-c0a34d46e84e.png)

2021-05-21 08:31 UTC, roecla approved these changes
Everything seems to work now. Thanks for all the fixes!

2021-05-21 08:31 UTC, merged